### ISSUE TITLE
[feat] Keep Find/Replace dialog open even if user clicks out

### ISSUE THREAD

**Issue by IAHawk** [phcode-dev/phoenix#1058]
### Describe the problem

Find/Replace dialog closes when user clicks into file.

### Describe the solution you'd like

Would be useful to select text from the content to use in the find/replace dialog box. The box should stay active while interacting with the file.

### Additional context

I am using Brackets Release 2.2 build 2.2.0-17942 (master c7a435e49) 
build timestamp: Sat Mar 11 2023 12:13:01 GMT+0530 
on a MacBook Pro M1

**Comment by IAHawk** [comment]
Finally recognized this behavior is controlled via the "autoHideSearch" preference setting.

**Comment by abose** [comment]
@IAHawk Thanks for raising the issue. It looks like most other editors dont auto close the bar. I too find the auto close behavior not that ux friendly.

Will make that as the default behavior from next update.
