### ISSUE TITLE
Keybinds Non-US Layout Z and Y Switched (Affects Undo Redo)

### ISSUE THREAD

**Issue by SVNKoch** [phcode-dev/phoenix#1078]
### Describe the bug

on non-US keyboard layouts the Z and Y key locations are switched. The menu entry says undo (CTRL + Z), but actually I have to press CTRL + Y to get undo. For redo it's the opposite.

### Reproduction

Use non-US layout (I'm using German), press CTRL+Z on your keyboard => nothing happens, press CTRL+Y => undo happens

### Expected behavior

CTRL+Z runs undo and CTRL+Y runs redo

### OS, Browser and Phoenix versions

windows 8.1
firefox 112
keyboard layout German
phoenix 3.2.1-19289

**Comment by abose** [comment]
Thanks for logging this issue @SVNKoch 
Will fix this in the coming releases.
