### ISSUE TITLE
[feat]  Visual Color Display Feature for CSS Hex Codes in phocode.dev Editor

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#1207]
### Describe the problem

CSS hexadecimal color codes are not visually descriptive, requiring developers to hover to preview colors.

### Describe the solution you'd like

Develop a feature for phocode.dev that displays color swatches next to the CSS hex codes within the editor. This should include a side panel with a color legend and inline color blocks adjacent to each hex code, as exemplified by the uploaded image. The color blocks should match the color of the hex code they represent, providing immediate visual feedback.
![Screenshot from 2023-11-27 21-36-11](https://github.com/phcode-dev/phoenix/assets/1525027/0d288046-6058-44ef-bc0e-d3f1f9fa3d02)

### Alternatives considered

This enhancement will streamline the workflow for developers and designers, facilitating quick color identification and management within the CSS codebase.

**Comment by abose** [comment]
We can do this in 2 ways:
1. [color hilighter extension](https://github.com/Taraflex/Brackets-Color-Highlighter) ![image](https://github.com/phcode-dev/phoenix/assets/5336369/f29c70b9-a1c8-4d42-8b04-391d750e32fc)
2. color picker as shown above.

**Comment by abose** [comment]
This is now done via color gutter. https://github.com/phcode-dev/phoenix/pull/1954  and https://github.com/phcode-dev/phoenix/pull/1963
 Closing.

Pending https://github.com/phcode-dev/phoenix/pull/1979 not merged due to UX issues.
