### ISSUE TITLE
[feat] Multi line find and replace

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix#1209]
### Describe the problem

Brackets is not able to find/replace multiple lines of code.

For instance, searching for:

<ul>
    <li>Cool</li>
    <li>Cold</li>
</ul>
and replacing it with:

<ul>
    <li>Room Temp</li>
    <li>Cool</li>
    <li>Cold</li>
    <li>Frozen</li>
</ul>
Across a single file, or multiple project files.

### Describe the solution you'd like

Existing find and replace in a single or multiple file should work as expeced.

### Alternatives considered

A minimal implementation is checked into branch `multiLineFind` in this repo. The implementation already works but there are some ux issues and layout issues to fix before we roll this out

1. Resizing the text area causes layout isses in status bar or find results panel
2. in find in single file mode, pressing sift-enter will cycle back through the results instead of creating a new line. This is the same behavior in vscode too, so that isnt a problem. Pressing down arrow/up arraw needs to be consistant
3. In multip file mode, in our case, pressing up and down arrow will cycle through reluts in results panel instead of moving cursor in multi file text. This could be frustrating as arrow keys work in single file mode and user may expect it to work same in multi file mode as well. We need to have a consistent UX. Maybe disable up/down arrow keys for cursor movement in both single/multi file mode. to be consistant.

### Additional context

https://www.reddit.com/r/brackets/comments/1890owj/question_finding_replacing_multiple_lines/

related: https://github.com/phcode-dev/phoenix/issues/1040

**Comment by vishae** [comment]
Hi,
I see that this request is considered closed and completed, but I still can't seem to find/replace multiple lines. Is there some settings I'm supposed to turn on, or a plugin I'm supposed to download?

I'm running Release 4.0 build 4.0.3-20878

**Comment by abose** [comment]
@vishae Multi like search is currently supported, but replace isnt.
This is now tracked as https://github.com/phcode-dev/phoenix/issues/2419
Thanks for reporting

**Comment by vishae** [comment]
> [@vishae](https://github.com/vishae) Multi like search is currently supported, but replace isnt. This is now tracked as [#2419](https://github.com/phcode-dev/phoenix/issues/2419) Thanks for reporting

Thanks for the explanation.
