### ISSUE TITLE
First load of themes take time

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#136]
### Prerequisites

* [ x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x ] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

It takes time to load first theme

### Steps to Reproduce
![Theams_not_loading](https://user-images.githubusercontent.com/1525027/138415870-d2fe2673-dc08-44c5-a682-babf9392fcb8.gif)

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the OS and what version of the OS you're running.
Please include the version of Brackets. You can find it under `Help -> About Brackets` (Windows and Linux) or `Brackets -> About Brackets` (macOS)

**Comment by abose** [comment]
Fixed. closing.
