### ISSUE TITLE
Feature request Icon_for visual cues for all file types

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#138]
![icon_webs](https://user-images.githubusercontent.com/1525027/138419613-a750eaad-2470-40b9-b7d9-b1443292f654.png)
![icon_vs_code](https://user-images.githubusercontent.com/1525027/138419621-591df492-b4c3-46c3-8fe4-8d95a4c4a4ae.png)

**Comment by abose** [comment]
done. closing.
