### ISSUE TITLE
Preview page: "Pin on Unpin" for "Pin or Unpin"

### ISSUE THREAD

**Issue by slel** [phcode-dev/phoenix#1528]
### Describe the bug

The contextual help for the pin icon at the top of the preview page reads
"Pin on Unpin Preview Page" instead of "Pin or Unpin Preview Page".

### Reproduction

Open a markdown file and its preview page;
the filename displays center of that page's top bar;
left of the filename one can see a pin icon.

Hovering over that pin icon, one reads
"Pin on Unpin Preview Page".

### Expected behavior

That should instead read "Pin **or** Unpin Preview Page", shouldn't it?

### OS, Browser and Phoenix versions

0. OS: linux
1. Device: laptop
2. Browser: Firefox
3. Version: Release 3.5 build 3.5.6-20070

### Additional context

This seems to correspond to the string
`LIVE_DEV_CLICK_TO_PIN_UNPIN`
in `src/nls/root/strings.js`.

https://github.com/phcode-dev/phoenix/blob/2f56133246254f25abbf4811159f2049e7c6237d/src/nls/root/strings.js#L153

If this indeed needs fixing, the translations will too.

**Comment by abose** [comment]
Oops Thanks for the report 😅. All strings are auto translated once the changes are pushed to tge root string file.
