### ISSUE TITLE
save as dialogue box not working.

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#153]
### Prerequisites

* [ X] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [ x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [ x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

save as from file menu does nothing

### Steps to Reproduce

1. click file > save as

**Expected behavior:** [What you expected to happen]
- Save as will show a dialog to set file name and extension

**Actual behavior:** [What actually happened]
- Save as does nothing
- save and save all is working as expected and saves all files without prompt.
![image](https://user-images.githubusercontent.com/78793827/138482506-bf4df5dd-cf1e-424d-b57e-be5db7374564.png)

Nothing happens other than the menu going away.

**Comment by abose** [comment]
`Save as` has been removed from browser version of phocode as its ux makes it a complicated workflow with browser Virtual fs.

The `duplicate` file/folder menu has been added to address most of the workflow needs. May reconsider feature for native builds.
