### ISSUE TITLE
Unable to uncomment Markdown files using keyboard shortcut or menu option

### ISSUE THREAD

**Issue by ayusht9** [phcode-dev/phoenix#1561]
### Describe the bug

The functionality to uncomment Markdown files via shortcut `ctrl+shift+/` or menu option does not work. 

This feature works for other languages.

### Reproduction

1. Open a Markdown file.
2. Comment a line using `ctrl+/` or menu.
3. Attempt to uncomment it using `Ctrl+Shift+/` or `ctrl + /` or the menu option. Notice that the uncommenting action does not have any effect on the Markdown file.

### OS, Browser and Phoenix versions

1. OS: Windows 10 Pro N
2. Version: Release 3.5 build 3.5.6-20070

**Comment by abose** [comment]
Thanks for raising the issue @ayusht9 Looks like a bug, will try to fix it this release or next.
