### ISSUE TITLE
macOS Big Sur -Phoenix Code Version 3.5.6 (20240327.085354) won't start correctly

### ISSUE THREAD

**Issue by StephenHellens** [phcode-dev/phoenix#1565]
### Describe the bug

When opening Phoenix Code, the following message appears in a dialogue: "Oops. Phoenix could not be started due to missing file system library download". See screenshot:

<img width="372" alt="Screenshot 2024-04-24 at 17 40 32" src="https://github.com/phcode-dev/phoenix/assets/11571721/09da8592-51dd-45fa-a4e7-16087f5f7276">

This doesn't happen with the in-browser version (Safari browser Version 16.6.1 (16615.3.12.11.5, 16615))

### Reproduction

1. Applications > Phoenix Code
2. Double click to open
3. Phoenix Code loads, the dialogue appears

### Expected behavior

Expect the application to launch as it does in the browser

### OS, Browser and Phoenix versions

1. macOS Big Sur 11.7.10 (20G1427)
2. MacBook Pro (Retina, 15-inch, Late 2013)
3. Safari browser Version 16.6.1 (16615.3.12.11.5, 16615)
4. Phoenix Code Version 3.5.6 (20240327.085354)

**Comment by abose** [comment]
Thanks for reporting the issue @StephenHellens 
Phoenix Code requires `macOS 12 Monterey` or higher because Apple introduced some system libraries starting with macOS 12, which Phoenix Code relies on. Apple doesnt seem to be patching `macOS Big Sur` with those updates (See image below).

![image](https://github.com/phcode-dev/phoenix/assets/5336369/1cde8b1f-6f09-4ffb-aae4-3570af257935)

**Comment by StephenHellens** [comment]
Thank you @abose for this information. Looks like I won't be able to give Phoenix Code a try as my hardware isn't supported beyond macOS Big Sur. It would be helpful if the [Phoenix Code download](https://phcode.dev/download/) page showed which versions of macOS are supported. Out of interest, where is the screenshot from?

**Comment by abose** [comment]
> Thank you @abose for this information. Looks like I won't be able to give Phoenix Code a try as my hardware isn't supported beyond macOS Big Sur. It would be helpful if the [Phoenix Code download](https://phcode.dev/download/) page showed which versions of macOS are supported. Out of interest, where is the screenshot from?

Wikipedia for Apple supported OS . Will add more info in the dialog specifying which platform is supported.

**Comment by abose** [comment]
Updated message: 

![Screenshot from 2024-04-27 10-51-58](https://github.com/phcode-dev/phoenix/assets/5336369/8e7c3259-e6f4-4948-8053-95e0e3caa835)

Closing as addressed. Thanks for reporting @StephenHellens
