### ISSUE TITLE
Phoenix Code installar breaks in Ubuntu 24.04

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#1612]
### Describe the bug

Installation fails in Ubuntu 24.04

### Reproduction

run `wget -qO- https://updates.phcode.io/linux/installer.sh | bash`

### OS, Browser and Phoenix versions

Ubuntu 24.04

**Comment by charlypa** [comment]
In Ubuntu 24.04 they have removed `libwebkit2gtk-4.0-37` from the default repo. Hence installation fails.

**Comment by abose** [comment]
Related to: https://github.com/tauri-apps/tauri/issues/9662

**Comment by charlypa** [comment]
This has been fixed in latest installer
