### ISSUE TITLE
Desktop version for Linux doesn't work on Fedora 40

### ISSUE THREAD

**Issue by jozsefk9** [phcode-dev/phoenix#1729]
### Describe the bug

Installation was successful: https://zigbin.io/1c4bd2

But after starting the app, it just keeps saying: Oops! Something went wrong. Trying to restart the app...

Screenshot attached.

![29Jun2024-22^23^07](https://github.com/phcode-dev/phoenix/assets/1645288/d3e63e88-26a6-4542-bbd0-476b7d3b4b46)

### Reproduction

1. Install it with `wget2 -qO- https://updates.phcode.io/linux/installer.sh | bash`
2. Run it with: `/home/jk/.phoenix-code/phoenix-code`

### OS, Browser and Phoenix versions

1. `Linux fedora 6.9.5-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Jun 16 15:47:09 UTC 2024 x86_64 GNU/Linux`
2. latest desktop app version

**Comment by abose** [comment]
Thanks for reporting the issue. Will investigate.

**Comment by charlypa** [comment]
@jozsefk9 
can you please try `sudo dnf update` and see if it fixes the issue

**Comment by charlypa** [comment]
@jozsefk9 
are you using fedora gnome or kde?

**Comment by jozsefk9** [comment]
> @jozsefk9 It looks likes your windowing manager is IceWM we have not tested Phoenix Code with it. I will test it is there a place where I can get iso for your OS?

I just used **Fedora Everything** from here: https://alt.fedoraproject.org/
Direct link: https://download.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/iso/Fedora-Everything-netinst-x86_64-40-1.14.iso

And installed the **Minimal Install** version, then after reboot I added things I need, among which were IceWM, LightDM and all other packages. In total, more than 1700 packages. That's what DNF does automatically actually, because it pulls the dependencies.

**Comment by charlypa** [comment]
![Screenshot from 2024-07-01 02-19-27](https://github.com/phcode-dev/phoenix/assets/1525027/1f5a3e8f-46a5-45dc-896a-ed940b35bab2)
I was able to make it work I doubt your theme is causing some issues

**Comment by jozsefk9** [comment]
Maybe. But then Phoenix is the only one application which doesn't work in this system. I tried many of them: Visual Studio Code, Geany, CudaText, Focus Editor, LiteXL, Lapce, Sublime Text, Kate, JetBrains Fleet... They all worked.

**Comment by charlypa** [comment]
@jozsefk9 
is there a way to share coredump to debug further

**Comment by charlypa** [comment]
@jozsefk9 
would you please share the output of following command 
`ldd /home/jk/.phoenix-code/phoenix-code`

**Comment by jozsefk9** [comment]
> @jozsefk9 would you please share the output of following command `ldd /home/jk/.phoenix-code/phoenix-code`

Yes please: https://zigbin.io/3e87dd

**Comment by abose** [comment]
> Maybe. But then Phoenix is the only one application which doesn't work in this system. I tried many of them: Visual Studio Code, Geany, CudaText, Focus Editor, LiteXL, Lapce, Sublime Text, Kate, JetBrains Fleet... They all worked.

To keep phcode as lightweight as possible, we use system installed components mostly. That however leads to some issues like this in configurations we have not accounted for in rare cases. And as we get reports like this, we fix the issues. Phcode is only 3 months old at this point in linux, so we still have a bit more work to do for universal support in linux. We are working on this, thanks for helping.

**Comment by charlypa** [comment]
@jozsefk9  There was an issue with default installation in fedora40. We just updated our script. could you please run installation with new script and see if it fixes your issue

**Comment by charlypa** [comment]
@jozsefk9 
If installation still fails would you please share output of below command

`sudo dnf list --showduplicates gstreamer1`

**Comment by jozsefk9** [comment]
> @jozsefk9 If installation still fails would you please share output of below command
> 
> `sudo dnf list --showduplicates gstreamer1` `sudo dnf list --showduplicates gstreamer1-plugins-base` `sudo dnf list --showduplicates gstreamer1-plugins-good`

Installation didn't seems to work, even though it says it was successful, because Phoenix behaves the same as it did before. This is the installation: https://zigbin.io/272dd3

GStremaer 1: https://zigbin.io/93879f

Plugins-Base: https://zigbin.io/0537a7

Plugin-Good: https://zigbin.io/d973fc

**Comment by charlypa** [comment]
@jozsefk9 
we doubt Phoneix is loading with an older version of Webkit. To confirm that would you please run the below command and share the results

` sudo find / -name WebKitWebProcess`

**Comment by jozsefk9** [comment]
> @jozsefk9 we doubt Phoneix is loading with an older version of Webkit. To confirm that would you please run the below command and share the results
> 
> ` sudo find / -name WebKitWebProcess`

Here is the result:
```
/usr/libexec/webkit2gtk-4.1/WebKitWebProcess
/usr/libexec/webkitgtk-6.0/WebKitWebProcess
/usr/libexec/webkit2gtk-4.0/WebKitWebProcess
```

**Comment by abose** [comment]
> > @jozsefk9 we doubt Phoneix is loading with an older version of Webkit. To confirm that would you please run the below command and share the results
> > 
> > ` sudo find / -name WebKitWebProcess`
> 
> Here is the result:
> ```
> /usr/libexec/webkit2gtk-4.1/WebKitWebProcess
> /usr/libexec/webkitgtk-6.0/WebKitWebProcess
> /usr/libexec/webkit2gtk-4.0/WebKitWebProcess
> ```

I will shate a custom debug build to troubleshoot this by tomorrow. We are unable to recreate this issue otherwise from tge isos.

**Comment by jozsefk9** [comment]
@abose 

I filtered out only the errors and expanded them. See if this is good enough for you:
https://zigbin.io/f016f8

**Comment by abose** [comment]
Can you paste the full error logs? It appears that most of the boot-time Tauri API calls failed. Will be good to have more context. Also I was unable to repro the issue from my end. Can you provide some step by step instructions on the exact iso's used/how to setup the machine for the configuration you are using. That will help me isolate the issue better.

**Comment by jozsefk9** [comment]
@abose 

Here is the complete log: https://zigbin.io/bd0b8c

ISO is the one I mentioned earlier: https://download.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/iso/Fedora-Everything-netinst-x86_64-40-1.14.iso

I installed the option: Minimal Install. And I checked NOTHING at all from the right side of the screen. Then after reboot I added the packages I need:

`ImageMagick alacritty bat bluez bzip2 cups cups-pdf firefox fuse git google-noto-color-emoji-fonts google-noto-emoji-fonts gtk2 gtk3 gtk4 gvfs-mtp helix icewm icewm-data icewm-minimal-session icewm-themes imwheel jmtpfs libxkbcommon-x11 lightdm mc nemo numlockx pipewire qt5pas-devel qt6-qtbase sane-backends-libs scribus smartmontools tesseract-langpack-srp tesseract-langpack-srp_latn unzip wget2 xev xorg-x11-server-Xorg xsel xset zstd opensc pcsc-lite-acsccid`

Then I enabled rpmfusion and installed more packages, with --allowerasing option:

`blender bluez-tools btop ffmpeg gimp gparted hunspell-sr hyphen-en hyphen-sr inkscape intel-media-driver java-latest-openjdk keepassxc libnsl libreoffice libvdpau-va-gl meld mpv mupdf nodejs obs-studio perl-Image-ExifTool python3-ansi2html thunderbird vlc yt-dlp gxkb --allowerasing`

More or less that's it.

**Comment by abose** [comment]
Thanks for the details. I will try recreating the issue locally.

**Comment by jozsefk9** [comment]
Of course you have to: `sudo systemctl enable lightdm`
and: `sudo systemctl set-default graphical.target`

**Comment by abose** [comment]
@jozsefk9 Can you see if this build works?
https://github.com/abose/wer/releases/download/fedoraDebug/portable.debug-2.zip

**Comment by jozsefk9** [comment]
@abose 
It's working fine now :)

**Comment by abose** [comment]
🥳 fix should be available in next release. Till then the build i shared should help. If there is anything to fix/any feature requests, please create an issue here.

**Comment by abose** [comment]
A release is planned for this week with the fix.

We've added your name to the release credits to acknowledge your help. If you would like to modify how your name appears, or prefer to be omitted from the release credits, please let us know by commenting here before September 3rd, @acemi1.
![image](https://github.com/user-attachments/assets/4d6963ae-3324-4099-840f-cd06672af777)

**Comment by abose** [comment]
A release is planned for this week with the fix.

We've added your name to the release credits to acknowledge your help. If you would like to modify how your name appears, or prefer to be omitted from the release credits, please let us know by commenting here before September 3rd, @jozsefk9 .
![image](https://github.com/user-attachments/assets/4d6963ae-3324-4099-840f-cd06672af777)

**Comment by jozsefk9** [comment]
> A release is planned for this week with the fix.
> 
> We've added your name to the release credits to acknowledge your help. If you would like to modify how your name appears, or prefer to be omitted from the release credits, please let us know by commenting here before September 3rd, @jozsefk9 .
> ![image](https://github.com/user-attachments/assets/4d6963ae-3324-4099-840f-cd06672af777)
> 

Great! Jozsef is fine. Thank you!
