### ISSUE TITLE
Crashing - "Phoenix Code quit unexpectedly"

### ISSUE THREAD

**Issue by drveresh** [phcode-dev/phoenix#1744]
### Describe the bug

For the last two days, the Phoenix app has been crashing without any error on the UI.

### Reproduction

Open the app on the taskbar, then it crashes immediately.crashes

### Expected behavior

Open the app and allow editing files

### OS, Browser and Phoenix versions

Model: MacBookPro18,1, BootROM 10151.121.1, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: Apr  4 2024 20:37:43 version 20.103.14.0.8.7.174 FWID 01-95f1e684
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

### logs or debug stack trace if any

```shell
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Phoenix Code [20454]
Path:                  /Applications/Phoenix Code.app/Contents/MacOS/Phoenix Code
Identifier:            io.phcode
Version:               3.7.3 (20240525.134214)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2024-07-10 00:45:01.6256 +0530
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        31774733-45FA-BABA-2020-33453E833C63

Sleep/Wake UUID:       D823AB51-4134-4A0D-8835-E9C415DB0992

Time Awake Since Boot: 18000 seconds
Time Since Wake:       4875 seconds

Notes:
PC register does not match crashing frame (0x8E449C70AA1B9F74 vs 0x1C70AA1B9F74)

Crashed Thread:        0  main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x8e449c70aa1b9f74 -> 0x00001c70aa1b9f74 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x8e449c70aa1b9f74

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [20454]

VM Region Info: 0x1c70aa1b9f74 is not in any region.  Bytes after previous region: 30789179514741  
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  reserved VM address space (unallocated)
--->  
      UNUSED SPACE AT END
```

**Comment by abose** [comment]
We have released a fix for this last week. Please download the latest build from phcode.io

**Comment by abose** [comment]
Closing as fixed. Please reopen if you are still facing any issues with the new builds @drveresh
