### ISSUE TITLE
error with Restart node 

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#176]
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

Restart node causing error

### Steps to Reproduce

1. click debug
2. click restart node

**Expected behavior:** [What you expected to happen]
no error
**Actual behavior:** [What actually happened]
Error message popping up

![error](https://user-images.githubusercontent.com/78793827/138889794-eeedb71e-3975-4e5d-90f3-2c6a774f750a.png)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/78793827/138893393-4b809416-01e1-4423-a7c8-8fac2b91b096.gif)

**Comment by abose** [comment]
Node removed from phoenix. closing.
