### ISSUE TITLE
[feat] Automatic indentation detection

### ISSUE THREAD

**Issue by albert200000** [phcode-dev/phoenix#1774]
### Describe the problem

I want editor to set indentation level automatically based on code in file.

### Describe the solution you'd like

The extension that worked for me [https://github.com/hirse/brackets-detect-indentation](https://github.com/hirse/brackets-detect-indentation). Can it be used without node?

**Comment by abose** [comment]
Thanks for reporting the issue. This is a good feature to have. Let me see if i can add this in the next release.

**Comment by abose** [comment]
Feature added via https://github.com/phcode-dev/phoenix/pull/1806
@albert200000  This will be avilable in the next release. Thanks for the feature request.
closing as done.
