### ISSUE TITLE
Desktop version for Linux doesn't work on Peppermint Devuan

### ISSUE THREAD

**Issue by Luka2552** [phcode-dev/phoenix#1783]
### Describe the bug

Installation was successful, however when I try to launch the code editor or open a folder with the code editor, a window pops up with nothing in it. (See attached image)

![PhoenixCodeBug](https://github.com/user-attachments/assets/dee4fc6c-079b-4121-a688-7ce08553188c)

### Reproduction

Installed it with wget -qO- https://updates.phcode.io/linux/installer.sh | bash
Opened it from the start menu (blank window pops up)
Opened a folder with phoenix code editor (blank window pops up)

### OS, Browser and Phoenix versions

1. Please see the attached neofetch image.
![neofetch](https://github.com/user-attachments/assets/09ad3620-ad3c-4bb0-bfb1-4757e040a615)

2. latest desktop app version

**Comment by Luka2552** [comment]
Proof of Re-install (See attached image)

![Reinstall Proof](https://github.com/user-attachments/assets/5d4e4ff8-eae8-43e5-8d39-1f3cc2ce6fce)

**Comment by charlypa** [comment]
@Luka2552 It seems this might be related to a driver issue with WebKitGTK. Could you try adding `WEBKIT_DISABLE_DMABUF_RENDERER=1` to your `/etc/environment` file and see if that resolves the problem?

**Comment by Luka2552** [comment]
It worked! cheers!
