### ISSUE TITLE
Stability: Node crash on computer sleep - below our stability target

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix#1791]
### Describe the bug
**About 10% of total desktop userbase is affected from metrics** . So marking as high priority to address before next release.
## Problem report:
`From what I can tell, every time my computer (Dell running Windows 10) goes into sleep mode, when I wake it and return to Phoenix Code (desktop), I get an "Oops! Something went wrong!" message with the error code ERROR_NODE_JS_CRASH. This wasn't the case when I first installed the Phoenix desktop app, it started in May or June, and I can't think of anything that changed in my environment. Has anyone else seen this, or does anyone have any ideas to solve this issue?`

See: https://github.com/orgs/phcode-dev/discussions/1790

This is only a problem in desktop builds and should not be limited to just windows OS.

### Reproduction
sleep and awake with phoenix open

### Expected behavior

no node crash

### OS, Browser and Phoenix versions

All desktop versions

### Metrics for node.crash.dlgShown
* about 10% of total desktop userbase is affected.
* Ignore the user spike in the metric post july 14. The spikes are due to incoming Brackets users after our july 14 brackets notification.
* The crash relative to the total number of users is constant. So its most likeley not a regression.
* The y-axis in the below graph is the number of users who experienced the crash in a week(7 days).

![image](https://github.com/user-attachments/assets/6f175edf-4da0-4261-b957-c0d7c8a51449)

**Comment by souscrire** [comment]
I've had this problem on two machines running windows 10. When will this be fixed please?

**Comment by abose** [comment]
@souscrire  The issue is fixed and should be available in the release planned for this week.
