### ISSUE TITLE
Firefox: No live preview in web editor on a windows machine

### ISSUE THREAD

**Issue by paintdog** [phcode-dev/phoenix#1854]
### Describe the bug

I'm using your web editor on a Windows machine with Firefox. After starting, the editor is unable to display a live preview and instead shows a GitHub information page.

### Reproduction

I start the editor in the browser and attempt to launch the live preview, but no live preview is available.

### Expected behavior

On my Linux machine, the editor is able to display a preview in the Firefox browser.

### OS, Browser and Phoenix versions

1. windows
1. desktop - web version
2. firefox
3. Release 3.9 build 3.9.5-20563 

### Additional context

I will add a screen cast or a screen shot as soon as possible.

**Comment by abose** [comment]
Please make sure that the firefox build is recent(within the last 3 years).
NB: Phoenix Code will not work in private window in Firefox as indexed DB is disabled in Private windows in firefox.

**Comment by paintdog** [comment]
It was the browser version. An update solved my problem. Sorry for the disturbance! Great work, everyone.

**Comment by abose** [comment]
No worries, please do log any issues you encounter in the future. 

Firefox does not support working with local files yet, so while firefox is supported the usability may be a bit less. Use the native apps to work with local files if a chromium based browser is not preferred.
