### ISSUE TITLE
[feat] can't read on the desktop app why can I not increase the size of the code i'm typing 

### ISSUE THREAD

**Issue by SamduJour** [phcode-dev/phoenix#1865]
### Describe the problem

I NEED TO SEE WHAT I AM WRITING. HOW IS THIS NORMAL.

### Describe the solution you'd like

I would like this app to function like the majority of apps on my computer instead of needing to sit 6" from the screen to see it.

### Alternatives considered

There are no alternatives, just lack of inclusion and accessibility.

### Additional context

No search: online, in the phoenix product forum, on the product itself, yield any solution to this problem. And ALL, I mean 100%, assume you are asking about how to type the html code which would enlarge code on your webpage.

**Comment by abose** [comment]
There are various zoom options already available. Please use the zoom options under view menu.

![Screenshot_20240922_073014_Chrome.jpg](https://github.com/user-attachments/assets/072d51ac-f775-4e26-8497-8d25115a4a25)

**Comment by abose** [comment]
Closing as zoom feature already exist. Please reopen if you face any issues with zoom

**Comment by SamduJour** [comment]
thank you. Realized it was actually an issue with my macbook not zooming on any app except chrome and a restart fixed. sorry for my outburst
