### ISSUE TITLE
Need to see actual path of file

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#189]
Phoenix should show the actual and relative path of file
![relative_file_path](https://user-images.githubusercontent.com/1525027/139580488-dbc65c9b-121e-43b7-8b96-7267481f6d97.gif)

**Comment by abose** [comment]
Copy path option is now supported: 
![image](https://github.com/phcode-dev/phoenix/assets/5336369/1039c70c-a4d2-4066-b674-bbf24f0d8768)
