### ISSUE TITLE
Ubuntu 24.10 Install fails

### ISSUE THREAD

**Issue by kelwynthedog** [phcode-dev/phoenix#1981]
### Describe the bug

Ubuntu 24.10 install fails:

1.  **Error:**  "Unable to locate package libwebkit2gtk-4.0-37".  **Resolved** by changing installer.sh line 252 to libwebkit2gtk-4.1-0

2. **Error:**  "libjavascriptcoregtk-4.0.so.18: cannot open shared object file: No such file or directory ".   **Resolved** with a symbolic link        ln  -s  /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.1.so.0  /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18 

3**.Error:**  "libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported."   Libsoup-2.4-1 and libsoup-3.0-0 both exist in the installation.  Removing either libsoup2 or libsoup3 will remove numerous applications and break the Mate desktop / Gnome desktop. (As suggested by Synaptic when marked for removal).

    

### Expected behavior

Install with no errors

### OS, Browser and Phoenix versions

Ubuntu 24.10
Chrome Version 130.0.6723.69 (Official Build) (64-bit)
MATE 1.26.2 on x11
Phoenix installer from web dated 10 Dec 2024

### logs or debug stack trace if any

```shell
./installer.sh: line 456: 10686 Trace/breakpoint trap   (core dumped) "$TMP_DIR/phoenix-code/phoenix-code" --runVerify
Verification failed even after installing dependencies.
```

**Comment by abose** [comment]
### Also happens in

OS: Linux Mint 22
Phoenix Code Version: 3.10.0
From: phoenix-code_3.10.0_amd64_linux_bin-GLIBC-2.35.tar.gz
GLIBC is version 2.39-0ubuntu8.3

**Comment by abose** [comment]
Thanks for the report and suggested fixes @kelwynthedog 

@charlypa looks like some deps in the closure changed again in Ubuntu like distros. Maybe we should turn to appimage in Linux for broader support, but the startup performance and memory usage/ligthweighterness of appimage will not match the our present app which reuses existing loaded system libs. Maybe use appimage as last resort or something if the install script fails to obtain the despondency closure.

**Comment by kelwynthedog** [comment]
@charlypa Many thanks, the installation was successful, Phoenixcode appears to function correctly on initial use.  During the install the following message appeared:  

(process:126216): libsoup-ERROR **: 10:17:31.774: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
main: line 464: 126216 Trace/breakpoint trap   (core dumped) "$TMP_DIR/phoenix-code/phoenix-code" --runVerify
Ubuntu 24.04 detected. Attempting to download and install GTK and WebKit2GTK...
Downloading GTK from https://github.com/phcode-dev/dependencies/releases/download/v1.0.3/gtk.tar.xz...
/tmp/tmp.5H7AkSD3Hv/gtk.tar.xz           100%[=================================================================================>]  35.17M  4.42MB/s    in 8.0s    
Extracting GTK...
Downloading WebKit2GTK from https://github.com/phcode-dev/dependencies/releases/download/v1.0.3/webkit2gtk-4.0.tar.xz...
/tmp/tmp.5H7AkSD3Hv/webkit2gtk-4.0.tar.x 100%[=================================================================================>]  38.38K  --.-KB/s    in 0.01s   
Extracting WebKit2GTK...

At this point all OK  Note the install detected 24.04, the version installed is 24.10.

As before, many thanks for the rapid resolution. Above and beyond!

**Comment by nekromoff** [comment]
Downloaded installer  from the website and it fails as mentioned in this bug report. Either fix that installer or reopen this bug.

**Comment by charlypa** [comment]
@nekromoff Installer is working fine for me on Ubuntu 24.10. Could you share a screenshot of the error you're getting? This would help us pinpoint what's different in your setup.

**Comment by nekromoff** [comment]
```
wget -qO- https://updates.phcode.io/linux/installer.sh | bashUsing temporary directory /tmp/tmp.D5TD8pBSLn for processing
Fetching the latest release information from phcode-dev/phoenix-desktop...
Current GLIBC version: 2.39
Searching for a compatible binary...
Found a new best match: https://github.com/phcode-dev/phoenix-desktop/releases/download/prod-app-v4.0.3/phoenix-code_4.0.3_amd64_linux_bin-GLIBC-2.31.tar.gz with GLIBC version 2.31
Found a new best match: https://github.com/phcode-dev/phoenix-desktop/releases/download/prod-app-v4.0.3/phoenix-code_4.0.3_amd64_linux_bin-GLIBC-2.35.tar.gz with GLIBC version 2.35
Downloading the compatible binary from https://github.com/phcode-dev/phoenix-desktop/releases/download/prod-app-v4.0.3/phoenix-code_4.0.3_amd64_linux_bin-GLIBC-2.35.tar.gz...
/tmp/tmp.D5TD8pBSLn/phoenix-code 100%[=========================================================>]  82,53M  71,6MB/s    in 1,2s
Downloading the icon...
/tmp/tmp.D5TD8pBSLn/icon.png     100%[=========================================================>]  41,14K  --.-KB/s    in 0,004s
Extracting the binary to /tmp/tmp.D5TD8pBSLn...

(process:164096): libsoup-ERROR **: 01:19:31.074: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is notsupported.
main: line 463: 164096 Trace/breakpoint trap   (core dumped) "$TMP_DIR/phoenix-code/phoenix-code" --runVerify
Initial verification failed. Attempting to install dependencies...
Attempting to install required dependencies...
The installation of dependencies requires administrative access. You may be prompted to enter your password.
Unsupported distribution. Please manually install the required dependencies.
```

before that it complained about both missing libraries that I symlinked.

**Comment by charlypa** [comment]
Would you be able to let me know the os details?

**Comment by nekromoff** [comment]
KDE Neon, so basically Ubuntu. If you are matching distribution name, then remember user agent matching in browsers. It is unreliable in similar way and not recommended.

```
Distributor ID: Neon
Description:    KDE neon 6.3
Release:        24.04
Codename:       noble
```

**Comment by nekromoff** [comment]
It works, thanks!
