### ISSUE TITLE
File tree refresh not happening automatically

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#310]
**Describe the bug**
After adding a new file to the folder via terminal, file tree refreshes are not in UI.

**To Reproduce**
1. Copy a file to the project folder via terminal
2. Check the Phoenix file UI
3. File not in the file  tree
4. Refresh the folder

**Expected behavior**
Once the file is copied to the project folder, it should be reflected automatically in the file tree.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Win10
 - Browser  Edge

**Comment by abose** [comment]
Closing as fixed
