### ISSUE TITLE
option to remove an imported folder is missing

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#312]
**Describe the bug**
we don't get an option to delete/remove a folder, which is imported using the  ' file -->import folder ' option.
**To Reproduce**
1. Please  go to the file section  and import a folder 
2. now right-click on the imported folder in the side panel
3. we see that option to remove the imported folder is missing   

**Expected behavior**
An option to delete/remove the folder from the tree will appear in right-click menu

**Screenshots**

![image](https://user-images.githubusercontent.com/78793827/154675434-4d6b4042-3ae3-4210-869e-914c42226095.png)

**Desktop :**
 - OS: ubuntu 21.10
 - Browser: chrome

**Comment by abose** [comment]
The project select/add/remove option is now present in the more visible new project dialogue as well.
Closing as improved.
