### ISSUE TITLE
auto-save feature 

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#408]
**Is your feature request related to a problem? Please describe.**

Please consider adding an auto-save feature.

 In low to medium spec machines, there is a probability of browser crashing (at random)on extended use. so an auto save feature would be really helpful to avoid data loss  

**Describe the solution you'd like**

triggering save automatically (may be every 2 minutes  )

**Comment by abose** [comment]
This has become a bug as Chrome has introduced [memory-saver](https://blog.google/products/chrome/new-chrome-features-to-save-battery-and-make-browsing-smoother/) feature, which just unloads a browser tab without warning and may lead to customer losing data after some inactivity. We need to add transparent data recovery to address this.

**Comment by abose** [comment]
Closing as we have a crash recovery feature. Autosave is available via extensions.
