### ISSUE TITLE
Bug: creating new project from github is failing for some repos

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#484]
**Describe the bug**
"new project from github" is failing for some repos with error message saying " urls which are larger than 25 mb is not allowed" while the download size of the project is less than 1 mb
**To Reproduce**
1. Go to 'phcode.dev'
2. select github in new project section
3. See error

**Expected behavior**
phoenex download and load the project for editing

**Screenshots**
![image](https://user-images.githubusercontent.com/78793827/173825512-a2a7c9b5-bfac-477c-8c3c-ce101ff2723e.png)
**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

**Comment by abose** [comment]
This is fixed. closing.
