### ISSUE TITLE
bug:pasting to root of a project not working

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#519]
**Describe the bug**
Pasting to the root (of project by clicking on empty space ) is not working.Currently paste function only works if right-clicked on a file or a folder
**To Reproduce**
1. From the file tree
2. Copy a file from a sub-directory
3. Paste it to the root of the file project by right-clicking blank space.

**Expected behavior**
The file should get pasted

**Screenshots**

https://user-images.githubusercontent.com/78793827/176169600-8a6cafa8-00ff-4197-8169-56d52eec12ae.mp4

**Additional context**
Issue related to https://github.com/phcode-dev/phoenix/issues/518

**Comment by abose** [comment]
@mathewdennis1 should be fixed with https://github.com/phcode-dev/phoenix/pull/521
Please check again

**Comment by mathewdennis1** [comment]
thankyou @abose, its working now.closing issue
