### ISSUE TITLE
enhancement: searching in a different file than the opened one  needs more visibility 

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#538]
**Describe the bug**
It could be a good idea to make it a bit more clear that we are searching in a different file than what we have opened..(people could accidentally right-click on a different file and won't realise it ..)
**To Reproduce**

1. open a file right click and select find function
2. right click on a different file to search 
3. see that it is very difficult to recognise that we are searching in a different file

**Expected behavior**
A clear indication that we are searching in a different file.
**Screenshots**

![177122401-6bdd2f3a-c3bb-41bd-a77](https://user-images.githubusercontent.com/78793827/177139557-68746e34-6e3a-4984-873e-9b65fad1a630.gif)

video -->https://user-images.githubusercontent.com/78793827/177122401-6bdd2f3a-c3bb-41bd-a779-7fbadf5c58fe.mp4

**Comment by mathewdennis1** [comment]
i would like to  recommend a small enhancement ,something like in the image below, when searching in other files.. (a popup bar on top  that would only show if we are searching in other files .if not we get the default behaviour

- this will give a visual confirmation  that ,we are actually searching in another file
- especially significant if there are large number of files with similar name .

![image](https://user-images.githubusercontent.com/78793827/177168480-0ecb302c-17bb-438b-a615-a18df188f3d0.png)


![image](https://user-images.githubusercontent.com/78793827/177168372-a3568ad9-f695-435d-8ac1-480ffdccfc8f.png)

**Comment by abose** [comment]
This is now fixed with: https://github.com/phcode-dev/phoenix/pull/1531
Thanks for the suggestion @mathewdennis1
