### ISSUE TITLE
Some (relatively new) CSS properties are  missing from the suggestions 

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#595]
### eg: space-evenly is missing in the list below
![Screenshot from 2022-08-03 21-09-20](https://user-images.githubusercontent.com/78793827/183047202-d8069fec-02a0-410c-8b4e-d20ee3bdbbc8.png)

**Comment by charlypa** [comment]
Phoenix does not provide valid suggestions for CSS attributes with `ctrl + space` pressed while editing CSS.
![msedge_ycQhIJZLVB](https://user-images.githubusercontent.com/1525027/211190887-b331b347-1371-439f-9de1-d885b5087299.gif)

**Comment by charlypa** [comment]
As a developer, I expect it to see valid suggestions when ctrl+space is clicked

**Comment by abose** [comment]
Properties updated. Closing.

**Comment by abose** [comment]
Pending: https://github.com/phcode-dev/phoenix/issues/1684
