### ISSUE TITLE
disable paste context menus in firefox.

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix#60]
Firefox does not support js initiated clipboard paste other than via extensions. Ctrl-c, Ctrl-V works though. 

## We should remove paste context menus from browsers that do not support navigator.clipboard functionality.

- [ ] Edit>paste menu
- [ ] document right click> paste
@abose

**Comment by PatriciaHeimfarth** [comment]
Hi, can I work on that issue please?

**Comment by abose** [comment]
Fixed, closing.
