### ISSUE TITLE
Make it possible to "install" Phoenix on Chrome OS

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix#694]
This Could be a good feature to have just for Chrome OS.

The reason it is not currently provided is that we are currently working on native builds for Win, Mac and, Linux.

Would prefer if there is a native option for chrome OS. If that is not available, Will enable the "install" feature in chromeOS.

related: https://github.com/phcode-dev/phoenix/discussions/693

**Comment by mblithium** [comment]
Agree, I have a chromebook and the options for code editors are limited, I could use the linux container and install Linux IDEs and code editors, but it's heavy for the simple hardware of chromebooks. The Phoenix project looks very promising and really lightweight, it uses APIs to access offline resources and would look great that way. It would also be great for education in schools, for example.

**Comment by abose** [comment]
Thanks for the details. Will check if i can do this in this months release along with windows, mac and linux native builds

**Comment by abose** [comment]
PWA support added to chrome OS. Will be available this/early next week.
