### ISSUE TITLE
Launch in Android Chrome says Browser Is Not Supported

### ISSUE THREAD

**Issue by Phtester2** [phcode-dev/phoenix#703]
![Screenshot_20221112-174837_Chrome](https://user-images.githubusercontent.com/118072589/201487736-c7813d23-4784-4d74-89f5-0ceb6460241f.jpg)

**Comment by abose** [comment]
@Phtester2 Thanks for raising the issue. Can you provide the following details:
Android version:
Chrome version:

@mathewdennis1 please verify / followup.

**Comment by abose** [comment]
Just saw the screenshot. @Phtester2 Phoenix is currently not natively supported in android and iOS, But we are working on a native version for mobile next year

**Comment by Phtester2** [comment]
Arun, Thanks.

I am interested to know why the supported Chrome is insufficient when OS is Android.

Meanwhile the response wording needs amendment to say so.

**Comment by abose** [comment]
Chrome in Android does not support opening and editing local device folders. So we cannot do 'open folder ' in Android. For that a native build will be available after we have shipped native builds on windows, mac and Linux

**Comment by abose** [comment]
> Arun, Thanks.
> 
> I am interested to know why the supported Chrome is insufficient when OS is Android.
> 
> Meanwhile the response wording needs amending to say so.

The response wording needs to change for mobile devices true! Thanks for the suggestion.

**Comment by Phtester2** [comment]
Thanks. Why is the supported Chrome insufficient when OS is Android?

**Comment by abose** [comment]
> Thanks. Why is the supported Chrome insufficient when OS is Android?

Chrome in Android does not support opening and editing local device folders. So we cannot do 'open folder ' in chrome Android. For that, a native build will be available after we have shipped native builds on windows, mac, and Linux

**Comment by Phtester2** [comment]
Thanks.

**Comment by abose** [comment]
Changed error messaging. Closing.
![image](https://user-images.githubusercontent.com/5336369/210152495-3dcb3058-a98a-4b07-b86f-8dba8b1b4fdc.png)
