### ISSUE TITLE
When in Default theme phoenix does not respond to OS toggling Dark-mode in chromium

### ISSUE THREAD

**Issue by mathewdennis1** [phcode-dev/phoenix#766]
**Describe the bug**
OS dark mode auto-swich does not work in phoenix running on chromium while it works on firefox. 
**To Reproduce**
1. Go to 'view > themes'
2. Change current theme to system default
3. Now toggle dark mode in os.

**Expected behavior**
Phoenix   respond to os changing to dark mode.
**Screenshots**
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/78793827/208250813-60dbee7d-4800-494a-ae63-fa3a0e777559.gif)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.10
 - Browser: chromium

**Comment by mathewdennis1** [comment]
https://developer.chrome.com/blog/auto-dark-theme/

**Comment by abose** [comment]
This is a chrome bug in linux/gnome as @mathewdennis1 pointed out.
Closing as it will be fixed in future gnome-chrome updates.

Works as expected in mac/windows/tauri.
Closing as there is nothing we can do from our end.
