### ISSUE TITLE
Live preview duplicate page while beautifying inline js in HTML

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#789]
**Describe the bug**
Live preview duplicate page while beautifying inline js

**To Reproduce**
1. open the following project in phoenix
[todohtml.tar.gz](https://github.com/phcode-dev/phoenix/files/10327231/todohtml.tar.gz)
 
2. open index.html
3. press `ctrl + b`
4.  press `ctrl +z`
5.  repeat 3 and 4

**Expected behavior**
A live preview should work normally

**Comment by abose** [comment]
Verified fixed.
Closing.
