### ISSUE TITLE
Putting debug break point freezes all livepreview windows

### ISSUE THREAD

**Issue by charlypa** [phcode-dev/phoenix#831]
### Describe the bug

Putting debug break point freezes all livepreview windows

### Reproduction

1. Pop out the live preview
2. Put debug breakpoint
3. make sure the code comes to breakpoint
4. See the code freezesthe 

### Expected behavior

Code should not freeze other open windows

### OS, Browser and Phoenix versions

Linux, Chrome

**Comment by abose** [comment]
Verified fixed in chrome and firefox.
Closing.
