### ISSUE TITLE
[feat] any long term plan of creating a desktop with tauri or electron 

### ISSUE THREAD

**Issue by zeet2020** [phcode-dev/phoenix#977]
### Describe the problem

any long term plan of creating a desktop with tauri or electron, 

### Describe the solution you'd like

desktop app like atom or vscode, but rather then using electron, something in tauri with smaller footprint

**Comment by abose** [comment]
@zeet2020 Thanks for the feature request.
Work in progress and should be out in two-three months. The[ native builds ](https://github.com/phcode-dev/phoenix-desktop)are based out of tauri.
 Please track in https://github.com/orgs/phcode-dev/projects/1

**Comment by abose** [comment]
Desktop app is now available at https://phcode.io
closing as done.
